Documentation and cleanup
glencoesoftware/jxrlib pull request #21
Opened 2020-02-05 02:30 UTC by melissalinkert

Adds a basic readme and Javadocs, and cleans up obvious things like copyright dates, repository URLs, and some duplicate code.  This includes the documentation requested in https://github.com/glencoesoftware/jxrlib/issues/14

In putting together this PR, I also noticed that the license in all of the ```pom.xml``` files is Simplified BSD, where the license at the top of every ```*.java``` file is GPL 2+.  Simplified BSD matches my assumption, but I haven't yet changed the headers in case that's incorrect.

The only behavior change should be in jxrlib-cli (```java/cli/```), which now actually compiles with Maven.  Gradle support is removed in 26d613d, because I really do not want to be supporting multiple build systems for the same Java code here.

2020-02-18 15:19 UTC, chris-allan commented
Upstream `JXRLIB-build` job that produces jxrlib-all utilizes `java/cli/build.gradle` for testing. Should we consolidate that somehow?

2020-02-25 21:56 UTC, melissalinkert commented
Reverted the commit that removes ```java/cli/build.gradle``` for now.  I'd prefer to reduce the number of build systems eventually, but it probably requires more time and thought than we have at the moment.

2020-05-05 17:58 UTC, chris-allan requested changes

2020-05-05 17:58 UTC, chris-allan commented on .travis.yml
> +  - mvn -f ../java/cli/pom.xml package
Needs to be removed now that the POM is gone.

2020-05-05 17:58 UTC, chris-allan commented on appveyor.yml
> +  - mvn -f java/cli/pom.xml package
As above.

2020-05-05 17:58 UTC, chris-allan commented on java/cli/pom.xml
File is gone, might cause merge conflicts.

2020-05-05 17:59 UTC, chris-allan commented
Probably needs to be rebased atop 0.2.x and the merge target changed or we can go with a second PR. Up to you @melissalinkert.

2020-05-05 21:24 UTC, melissalinkert commented
Rebased to 0.2.x and builds fixed.

2020-05-05 21:28 UTC, chris-allan approved these changes

2020-05-05 21:28 UTC, merged